#!/usr/bin/python
import socket, sys

sock = socket.socket()
sock.connect(('localhost', 4851))

map = {
    'toggle': 0,
    'play'  : 1,
    'pause' : 2,
    'prev'  : 3,
    'next'  : 4
}

code = map.get(sys.argv[1])
if code is not None: sock.send(chr(code))
